version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: minibank-postgres
    environment:
      POSTGRES_DB: pgminibank
      POSTGRES_USER: minibank
      POSTGRES_PASSWORD: minibank1234
    ports:
      - "2345:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
